apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: applicationsets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: apps-dev
  source:
    repoURL: https://github.com/unnamedid/platform-infra.git
    targetRevision: HEAD
    path: applicationsets
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
